### ISSUE TITLE
Can't load Decoder NIF - "unifex_create/0 is undefined"  

### ISSUE THREAD

**Issue by mickel8** [membraneframework/membrane_h264_ffmpeg_plugin#15]
Sometimes h264 NIF cannot be loaded with the following error

```
13:50:12.175 [error] GenServer #PID<0.530.0> terminating
** (UndefinedFunctionError) function Membrane.H264.FFmpeg.Decoder.Native.Nif.unifex_create/0 is undefined (module Membrane.H264.FFmpeg.Decoder.Native.Nif is not available)
    (membrane_h264_ffmpeg_plugin 0.5.0) Membrane.H264.FFmpeg.Decoder.Native.Nif.unifex_create()
    (membrane_h264_ffmpeg_plugin 0.5.0) lib/membrane_h264_ffmpeg/decoder.ex:29: Membrane.H264.FFmpeg.Decoder.handle_stopped_to_prepared/2
    (membrane_core 0.6.0) lib/membrane/core/callback_handler.ex:128: Membrane.Core.CallbackHandler.exec_callback/4
    (membrane_core 0.6.0) lib/membrane/core/callback_handler.ex:70: Membrane.Core.CallbackHandler.exec_and_handle_callback/5
    (membrane_core 0.6.0) lib/membrane/core/playback_handler.ex:115: Membrane.Core.PlaybackHandler.do_change_playback_state/2
    (membrane_core 0.6.0) lib/membrane/core/element/message_dispatcher.ex:83: Membrane.Core.Element.MessageDispatcher.do_handle_message/3
    (membrane_core 0.6.0) lib/membrane/core/element/message_dispatcher.ex:36: Membrane.Core.Element.MessageDispatcher.handle_message/3
    (stdlib 3.13) gen_server.erl:680: :gen_server.try_dispatch/4
```

but sometimes everything works fine. It looks like some kind of race condition?

**EDIT**: more stacktrace

```
13:55:37.142 [warn]  The on_load function for module Elixir.Membrane.H264.FFmpeg.Decoder.Native.Nif returned:
{:badarg, [{:erlang, :load_nif, [:erlang, :apply], []}, {Membrane.H264.FFmpeg.Decoder.Native.Nif, :load_nif, 0, [file: 'lib/membrane_h264_ffmpeg/decoder_native.ex', line: 1]}, {:code_server, :"-handle_on_load/5-fun-0-", 1, [file: 'code_server.erl', ...]}]}
```

**Comment by mat-hek** [comment]
It seems it's that issue: https://github.com/membraneframework/bundlex/issues/58, please reopen otherwise

**Comment by mickel8** [comment]
Yeap, it was probably this. With OTP 23.0.3 it works
